# TRMNLP configuration
---
watch:
  - .trmnlp.yml
  - src

# This is the "proper" place. 
# It works as {{resource_type}} in settings.yml 
# AND maps to trmnl.plugin_settings.custom_fields_values.resource_type in Liquid.
custom_fields:
  resource_type: "Electricity"

variables: {}